---

- include: redhat/centos/7/ca_certificate_trust.yml
  when: pki_is_centos7

- include: debian/ca_certificate_trust.yml
  when: pki_is_debian

- name: Get list of known certificates
  shell: grep -E -e '^[^#].*$' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: pki_register_ca_certificates_known
  changed_when: False

- name: Get list of untrusted certificates
  shell: grep -E -e '^!+' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: pki_register_ca_certificates_untrusted
  changed_when: False

- name: Get list of trusted certificates
  shell: grep -E -e '^[^#!].*$' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: pki_register_ca_certificates_trusted
  changed_when: False

- name: Get list of blacklisted certificates
  shell: grep -E -e '{{ pki_system_ca_certificates_blacklist | join("' -e '") }}' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: pki_register_ca_certificates_blacklist
  changed_when: False
  when: pki_system_ca_certificates_blacklist is defined and pki_system_ca_certificates_blacklist

- name: Get list of whitelisted certificates
  shell: grep -E -e '{{ pki_system_ca_certificates_whitelist | join("' -e '") }}' /etc/ca-certificates.conf | sed -e 's/^!//'
  register: pki_register_ca_certificates_whitelist
  changed_when: False
  when: pki_system_ca_certificates_whitelist is defined and pki_system_ca_certificates_whitelist

- name: Configure system CA certificates
  template:
    src: 'etc/ca-certificates.conf.j2'
    dest: '/etc/ca-certificates.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'Reconfigure ca-certificates' ]
