- name: Set default trust policy for new certificates
  debconf:
    name: 'ca-certificates'
    question: 'ca-certificates/trust_new_crts'
    vtype: 'select'
    value: '{{ "yes" if (pki_system_ca_certificates_trust_new | bool) else "no" }}'
